### PR TITLE
Run oc adm diagnostics once per day, and send failures to a given ema…

### PR DESCRIPTION
**Pull request by etsauer**
…il address

#### What is this PR About?
See title

#### How do we test this?
```
oc process -v=JOB_SERVICE_ACCOUNT=pruner -v=JOB_ALERT_EMAIL=esauer@redhat.com -f scheduledjob-diagnostics.json | oc create -f-
```

cc: @redhat-cop/day-in-the-life-ops

### CODE REVIEW

**Comment by sabre1041** [comment]
@etsauer Reviewed the PR. A couple of notes

1. By default, no output if generated
2. If removing the additional code and just performing `oc adm diagnostics`, the following is returned

```
[Note] Determining if client configuration exists for client/cluster diagnostics
[Note] No client configuration specified; skipping client and cluster diagnostics.
[Note] Summary of diagnostics execution (version v3.4.1.2):
[Note] Completed with no errors or warnings seen.
```

Would we want to execute more than a baseline check that it is doing?

**Comment by etsauer** [comment]
@sabre1041 is this PR still relevant?

**Comment by makentenza** [comment]
@etsauer @sabre1041 I think we can close this as `oc adm diagnostics` is going to be deprecated soon

**Comment by sabre1041** [comment]
@etsauer yes lets go ahead and close this

**Comment by oybed** [comment]
Closing per above comments

**Pull request closed without merging**
